# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='blog_image')),
            ],
        ),
    ]
