# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
