# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-01 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'galleries'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption',
            field=models.TextField(default='', null=True),
        ),
    ]
