# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-01 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170401_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
    ]
