# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
