# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_kind_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
