# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-28 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='person_image')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('spin_action', models.CharField(max_length=200)),
                ('description', models.TextField(default='', null=True)),
            ],
        ),
    ]
