# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-28 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20170328_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='people.Role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
