# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-17 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20170328_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
